---
- hosts: localhost
  gather_facts: false

  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    namespace: testing
    service_name: helloworld
    service_port: 11130

  tasks:
    - name: Expose application.
      include_tasks: tasks/k8s_expose.yml