- name: Create a HorizontalPodAutoscaler for "{{ service_name }}".
  k8s:
    state: present
    definition:
      apiVersion: autoscaling/v2beta2
      kind: HorizontalPodAutoscaler
      metadata:
        name: "{{ service_name }}"
        namespace: "{{ namespace }}"
      spec:
        scaleTargetRef:
          apiVersion: apps/v1
          kind: Deployment
          name: "{{ service_name }}"
        minReplicas: 1
        maxReplicas: 10
        metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 50